Repository ahmetilhn/zelzele.io, pull requests merged in 2023-03, with the labels that each got.

#13 Seo
  components/earthquake-list-item.vue
  nuxt.config.ts
  utils/string.util.ts
  yarn.lock
Labels: improvement

#14 👽 detail modal added
  assets/svg/eye.svg
  components/base-modal.vue
  components/detail-table.vue
  components/earthquake-list-item.vue
  components/earthquakes-chart.vue
Labels: enhancement, improvement

#19 Product hunt embed
  assets/scss/variables.scss
  assets/svg/eye.svg
  assets/svg/github.svg
  assets/svg/logo.svg
  components/earthquake-list-item.vue
  components/earthquakes-chart.vue
  components/partials/app-header.vue
  components/partials/bottom-bar.vue
  layouts/default.vue
Labels: enhancement, improvement

#26 google map source added, map created, data added
  components/partials/bottom-bar.vue
  interfaces/earthquake.interface.ts
  layouts/default.vue
  package.json
  pages/map.vue
  server/api/earthquakes.ts
  tsconfig.json
  utils/map.util.ts
  yarn.lock
Labels: enhancement

#28 Google map
  utils/map.util.ts
Labels: duplicate

#29 Refactor
  package.json
  pages/info.vue
  server/api/earthquakes.ts
  yarn.lock
Labels: improvement

#34 📉 download and share feature added
  components/base-modal.vue
  components/earthquake-list-item.vue
  package.json
  yarn.lock
Labels: enhancement

#36 wheel action zoom and zoom-out added
  utils/map.util.ts
Labels: enhancement

#37 sitemap improved
  public/sitemap.xml
Labels: improvement
