Repository ahmetilhn/zelzele.io, pull requests merged in 2023-02, with the labels that each got.

#1 Fix: Horizontal scroll problem.
  components/partials/app-header.vue
Labels: improvement

#2 Bottom Bar
  assets/img/promotion/earthquake-item-2.png
  assets/img/promotion/earthquake-item.png
  assets/img/promotion/mourn.png
  assets/scss/global.scss
  assets/scss/mixins.scss
  assets/scss/variables.scss
  components/bg-overlay.vue
  components/loader.vue
  components/partials/app-header.vue
  components/partials/bottom-bar.vue
  constants/menu.constants.ts
  layouts/default.vue
  package.json
  pages/index.vue
  pages/info.vue
Labels: bug, documentation, enhancement, improvement

#5 Chart improve
  components/earthquake-list-item.vue
  components/earthquakes-chart.vue
  components/tooltip.vue
  pages/index.vue
  pages/info.vue
  types/chart.type.ts
Labels: bug, improvement

#6 🧐 gtm added, events created
  components/earthquakes-chart.vue
  components/partials/bottom-bar.vue
  middleware/gtm-event.global.ts
  nuxt.config.ts
  plugins/gtm.plugin.ts
  types/gtm.type.ts
  utils/gtm.util.ts
Labels: enhancement

#8 🌍 afad data added
  components/earthquake-list-item.vue
  components/earthquakes-chart.vue
  components/earthquakes-list.vue
  interfaces/earthquake.interface.ts
  pages/info.vue
  server/api/earthquakes.ts
Labels: enhancement, improvement
